CREATE TABLE IF NOT EXISTS sop2_service_change_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    kode_perubahan VARCHAR(50) NOT NULL,
    pelanggan_id BIGINT UNSIGNED NOT NULL,
    kontrak_induk_id BIGINT UNSIGNED NOT NULL,
    lokasi_id BIGINT UNSIGNED NULL,
    lokasi_hasil_id BIGINT UNSIGNED NULL,
    jenis_permintaan VARCHAR(30) NOT NULL,
    lokasi_nama VARCHAR(200) NOT NULL,
    lokasi_alamat TEXT NOT NULL,
    lokasi_kota VARCHAR(100) NOT NULL,
    lokasi_provinsi VARCHAR(100) NOT NULL,
    lokasi_kode_pos VARCHAR(20) NULL,
    core_dedicated INT NOT NULL DEFAULT 0,
    sharing_core VARCHAR(10) NULL,
    core_sebelum VARCHAR(150) NULL,
    sharing_core_sebelum VARCHAR(10) NULL,
    catatan_pelanggan TEXT NULL,
    current_step TINYINT UNSIGNED NOT NULL DEFAULT 1,
    total_steps TINYINT UNSIGNED NOT NULL DEFAULT 12,
    status VARCHAR(30) NOT NULL DEFAULT 'diajukan',
    rejection_reason TEXT NULL,
    requested_by_user_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_sop2_kode_perubahan (kode_perubahan),
    KEY idx_sop2_pelanggan (pelanggan_id),
    KEY idx_sop2_kontrak_induk (kontrak_induk_id),
    KEY idx_sop2_status_step (status, current_step),
    CONSTRAINT fk_sop2_pelanggan FOREIGN KEY (pelanggan_id) REFERENCES pelanggan(id),
    CONSTRAINT fk_sop2_kontrak_induk FOREIGN KEY (kontrak_induk_id) REFERENCES lokasi(id),
    CONSTRAINT fk_sop2_lokasi FOREIGN KEY (lokasi_id) REFERENCES lokasi(id),
    CONSTRAINT fk_sop2_lokasi_hasil FOREIGN KEY (lokasi_hasil_id) REFERENCES lokasi(id),
    CONSTRAINT fk_sop2_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_sop2_jenis_permintaan CHECK (jenis_permintaan IN ('tambah_sharing_core', 'tambah_dedicated_core', 'lokasi_baru')),
    CONSTRAINT chk_sop2_core_dedicated CHECK (core_dedicated >= 0),
    CONSTRAINT chk_sop2_core_xor_sharing CHECK (core_dedicated = 0 OR sharing_core IS NULL OR TRIM(sharing_core) = '')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
