import { useState } from "react";
import { Loader2, Power, X } from "lucide-react";
import { updatePortalRegistrationActivation } from "../../lib/rust-api";

export default function ActivationModal({ isOpen, registration, session, onClose, onSuccess }) {
  const [status, setStatus] = useState("terjadwal"); const [jadwal, setJadwal] = useState(""); const [catatan, setCatatan] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  if (!isOpen || !registration) return null;
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await updatePortalRegistrationActivation(session.token, registration.id, { aktivasi_status: status, aktivasi_jadwal_at: status === "terjadwal" ? jadwal : null, aktivasi_catatan: catatan.trim() || null }); onSuccess?.(); onClose(); } catch (err) { setError(err.message || "Gagal memperbarui aktivasi."); } finally { setSaving(false); } };
  const updateJadwal = (event) => setJadwal(event.currentTarget.value);
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70" onClick={onClose}/><form onSubmit={submit} className="relative w-full max-w-lg rounded-2xl border border-white/10 bg-slate-900 p-6"><div className="mb-5 flex items-center justify-between"><div className="flex gap-3"><Power className="text-emerald-300"/><div><h2 className="font-semibold text-white">Aktivasi Layanan</h2><p className="text-xs text-slate-400">{registration.kode_registrasi} · {registration.lokasi_nama}</p></div></div><button type="button" onClick={onClose}><X className="text-slate-400"/></button></div><label className="block text-sm text-slate-200">Status *<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white"><option value="terjadwal">Terjadwal</option><option value="proses">Dalam proses ISP</option><option value="aktif">Layanan aktif</option></select></label>{status === "terjadwal" && <label className="mt-4 block text-sm text-slate-200">Jadwal aktivasi *<input required type="datetime-local" step="60" value={jadwal} onChange={updateJadwal} onInput={updateJadwal} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white"/></label>}<label className="mt-4 block text-sm text-slate-200">Catatan<textarea value={catatan} onChange={e=>setCatatan(e.target.value)} rows={3} className="mt-1.5 w-full rounded-lg border border-slate-600 bg-slate-950 p-3 text-white"/></label>{error&&<p className="mt-3 text-sm text-rose-200">{error}</p>}<button disabled={saving} className="mt-5 w-full rounded-lg bg-emerald-400 py-2.5 text-sm font-bold text-slate-950">{saving&&<Loader2 size={16} className="mr-2 inline animate-spin"/>}Simpan Aktivasi</button></form></div>;
}
