import { useCallback, useEffect, useState } from "react";
import { BadgeCheck, Building2, CheckCircle2, ClipboardCheck, FileCheck2, Loader2, Power, ReceiptText } from "lucide-react";
import { listPortalRegistrations, listServiceChangeRequests } from "../../lib/rust-api";
import LegalApprovalModal from "./LegalApprovalModal";
import SurveyRegistrationModal from "./SurveyRegistrationModal";
import ActivationModal from "./ActivationModal";
import CompletionModal from "./CompletionModal";
import PaymentVerificationModal from "./PaymentVerificationModal";
import Sop2ActionModal from "./Sop2ActionModal";
import { getSop1Owner, getSop2Owner } from "./workflowResponsibility";

const SETTINGS = {
  direksi: { title: "Persetujuan Direksi (opsional)", description: "Tinjau pengajuan yang telah diverifikasi KIMA. Admin KIMA/DBO menjadi pelaksana utama; Direksi dapat memberi keputusan bila dilibatkan.", icon: Building2, color: "violet" },
  teknisi: { title: "Antrean Teknis", description: "Tentukan jadwal dan selesaikan survei jalur, aktivasi layanan, serta berita acara aktivasi.", icon: ClipboardCheck, color: "sky" },
  keuangan: { title: "Tagihan & Pembayaran", description: "Terbitkan invoice setelah BAA diterima dan verifikasi bukti pembayaran pelanggan.", icon: ReceiptText, color: "amber" },
};
const ACCENT_CLASSES = { violet: { border: "border-violet-400/20", icon: "bg-violet-400/15 text-violet-200" }, sky: { border: "border-sky-400/20", icon: "bg-sky-400/15 text-sky-200" }, amber: { border: "border-amber-400/20", icon: "bg-amber-400/15 text-amber-200" } };
const SOP2_STEP_LABELS = { 2: "Kirim daftar tarif sesuai kontrak induk", 3: "Verifikasi jalur bersama pelanggan", 4: "Kirim PO dengan tarif kontrak", 6: "Siapkan dokumen perjanjian", 7: "Tanda tangani BAK", 8: "Aktifkan / sambungkan layanan", 9: "Kirim status aktivasi & BAA", 10: "Terbitkan invoice", 11: "Kirim tagihan ke pelanggan" };

function taskFor(role, row) {
  if (role === "direksi" && row.direksi_status === "menunggu") return { label: "Beri keputusan (opsional)", key: "direksi", Icon: Building2 };
  if (role === "teknisi" && row.survey_status === "belum_dijadwalkan") return { label: "Tentukan jadwal survei", key: "survey", Icon: ClipboardCheck };
  if (role === "teknisi" && row.survey_status === "terjadwal") return { label: "Selesaikan survei", key: "survey", Icon: ClipboardCheck };
  // BAA baru dapat dibuat setelah aktivasi benar-benar aktif. Sebelumnya
  // kondisi hanya memeriksa pks_status sehingga tombol aktivasi terus muncul
  // dan tahap BAA tidak pernah dapat dibuka dari antrean Teknisi.
  if (role === "teknisi" && row.pks_status === "lengkap" && row.aktivasi_status !== "aktif") return { label: "Perbarui aktivasi", key: "activation", Icon: Power };
  if (role === "teknisi" && row.aktivasi_status === "aktif" && row.baa_status === "belum_dibuat") return { label: "Buat BAA", key: "baa", Icon: FileCheck2 };
  if (role === "keuangan" && row.pembayaran_status === "menunggu_verifikasi") return { label: "Verifikasi pembayaran", key: "payment", Icon: BadgeCheck };
  if (role === "keuangan" && ["belum_dibuat", "draft"].includes(row.invoice_status)) return { label: "Buat & kirim invoice", key: "invoice", Icon: ReceiptText };
  return null;
}

export default function RoleWorkQueue({ session, role }) {
  const [rows, setRows] = useState([]); const [sop2Rows, setSop2Rows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [target, setTarget] = useState(null); const [sop2Target, setSop2Target] = useState(null);
  const setting = SETTINGS[role]; const accent = ACCENT_CLASSES[setting.color]; const HeaderIcon = setting.icon;
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [registrations, changes] = await Promise.all([listPortalRegistrations(session.token), role === "direksi" ? Promise.resolve([]) : listServiceChangeRequests(session.token)]); setRows(role === "teknisi" ? registrations.filter((item) => item.status === "disetujui") : registrations); setSop2Rows(changes); } catch (err) { setError(err.message || "Antrean belum dapat dimuat."); } finally { setLoading(false); } }, [session.token, role]);
  useEffect(() => { load(); }, [load]);
  const done = () => { setTarget(null); load(); }; const sop2Done = () => { setSop2Target(null); load(); };
  const actionableRows = rows.map((row) => ({ row, task: taskFor(role, row) })).filter((item) => item.task);
  return <div className="mx-auto w-full max-w-6xl">
    <section className={`rounded-2xl border ${accent.border} bg-gradient-to-br from-slate-900/90 to-slate-950/70 p-5 shadow-2xl`}><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className={`rounded-xl p-3 ${accent.icon}`}><HeaderIcon size={24} /></span><div><h1 className="text-xl font-black text-white">{setting.title}</h1><p className="mt-1 max-w-2xl text-sm text-white/60">{setting.description}</p></div></div><button type="button" onClick={load} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold text-white/70 hover:bg-white/10">Muat ulang</button></div></section>
    <section className="mt-5 rounded-2xl border border-white/10 bg-slate-950/55 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-black uppercase tracking-wider text-white/80">Perlu tindakan</h2><span className="rounded-full bg-white/10 px-2.5 py-1 text-xs font-bold text-white/70">{actionableRows.length}</span></div>{loading ? <div className="flex justify-center py-14"><Loader2 className="animate-spin text-sky-300" /></div> : error ? <p className="rounded-xl bg-rose-500/10 p-4 text-sm text-rose-200">{error}</p> : actionableRows.length === 0 ? <div className="rounded-xl border border-dashed border-white/15 py-14 text-center text-sm text-white/45">Tidak ada pekerjaan yang menunggu peran Anda.</div> : <div className="grid gap-3 md:grid-cols-2">{actionableRows.map(({ row, task }) => { const TaskIcon = task.Icon; const owner = getSop1Owner(row); return <article key={row.id} className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black tracking-wider text-sky-200">{row.kode_registrasi}</p><h3 className="mt-1 font-bold text-white">{row.lokasi_nama}</h3><p className="mt-1 text-xs text-white/50">{row.nama_perusahaan} · {row.pic_nama}</p></div><span className="rounded-md bg-white/10 px-2 py-1 text-[10px] font-bold text-white/60">{row.status}</span></div><div className="mt-3 rounded-lg border border-sky-400/15 bg-sky-400/10 px-3 py-2"><p className="text-[10px] font-black uppercase tracking-wider text-sky-200">Penanggung jawab</p><p className="mt-1 text-xs font-bold text-white">{owner.label}</p><p className="mt-0.5 text-[11px] text-white/55">{owner.stage}</p></div><button type="button" onClick={() => setTarget({ row, key: task.key })} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-sky-300 px-3 py-2 text-xs font-black text-slate-950 hover:bg-sky-200"><TaskIcon size={15} />{task.label}</button></article>; })}</div>}</section>
    {!loading && role !== "direksi" && <section className="mt-5 rounded-2xl border border-gold-accent/20 bg-slate-950/55 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-sm font-black uppercase tracking-wider text-white/80">SOP 2 · Perubahan layanan</h2><p className="mt-1 text-xs text-white/45">Permohonan sharing core, dedicated core, dan lokasi baru.</p></div><span className="rounded-full bg-gold-accent/15 px-2.5 py-1 text-xs font-bold text-gold-accent">{sop2Rows.length}</span></div>{sop2Rows.length === 0 ? <div className="rounded-xl border border-dashed border-white/15 py-10 text-center text-sm text-white/45">Tidak ada tahap SOP2 yang menunggu peran Anda.</div> : <div className="grid gap-3 md:grid-cols-2">{sop2Rows.map((item) => { const owner = getSop2Owner(item.current_step); return <article key={item.id} className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black tracking-wider text-gold-accent">{item.kode_perubahan}</p><h3 className="mt-1 font-bold text-white">{item.lokasi_nama}</h3><p className="mt-1 text-xs capitalize text-white/50">{item.nama_pelanggan} · {item.jenis_permintaan.replaceAll("_", " ")}</p></div><span className="rounded-md bg-gold-accent/10 px-2 py-1 text-[10px] font-bold text-gold-accent">Tahap {item.current_step}/12</span></div><div className="mt-3 rounded-lg border border-gold-accent/15 bg-gold-accent/10 px-3 py-2"><p className="text-[10px] font-black uppercase tracking-wider text-gold-accent">Penanggung jawab</p><p className="mt-1 text-xs font-bold text-white">{owner.label}</p><p className="mt-0.5 text-[11px] text-white/55">{owner.stage}</p></div><button type="button" onClick={() => setSop2Target(item)} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-gold-accent px-3 py-2 text-xs font-black text-slate-950 hover:bg-yellow-300"><CheckCircle2 size={15} />Proses tahap</button></article>; })}</div>}</section>}
    <LegalApprovalModal isOpen={target?.key === "direksi"} registration={target?.row} stage="direksi" session={session} onClose={() => setTarget(null)} onSuccess={done} /><SurveyRegistrationModal isOpen={target?.key === "survey"} registration={target?.row} session={session} onClose={() => setTarget(null)} onSuccess={done} /><ActivationModal isOpen={target?.key === "activation"} registration={target?.row} session={session} onClose={() => setTarget(null)} onSuccess={done} /><CompletionModal isOpen={target?.key === "baa" || target?.key === "invoice"} registration={target?.row} stage={target?.key} session={session} onClose={() => setTarget(null)} onSuccess={done} /><PaymentVerificationModal isOpen={target?.key === "payment"} registration={target?.row} session={session} onClose={() => setTarget(null)} onSuccess={done} /><Sop2ActionModal item={sop2Target} session={session} onClose={() => setSop2Target(null)} onSuccess={sop2Done} />
  </div>;
}
