import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Loader2, X } from "lucide-react";
import { completeServiceChangeStep, uploadDocument } from "../../lib/rust-api";

const CONFIG = {
  2: { action: "kirim_tarif", title: "Kirim daftar tarif", fields: [{ key: "tarif_catatan", label: "Tarif & catatan penawaran", type: "textarea", required: true }] },
  3: { action: "survei_jalur", title: "Verifikasi jalur", fields: [{ key: "survey_hasil", label: "Hasil survei jalur", type: "textarea", required: true }] },
  4: { action: "kirim_po", title: "Kirim PO bertarif", fields: [{ key: "po_nomor", label: "Nomor PO", required: true }], document: true, category: "Dokumen Lain" },
  5: { action: "submit_po", title: "Kirim PO ke KIMA", fields: [{ key: "po_nomor", label: "Nomor PO", required: true }], document: true, category: "Dokumen Lain" },
  6: { action: "siapkan_perjanjian", title: "Siapkan perjanjian", fields: [{ key: "perjanjian_nomor", label: "Nomor perjanjian / addendum", required: true }], document: true, category: "BAK-PKS" },
  7: { action: "tanda_tangan_bak", title: "Tanda tangan BAK", fields: [{ key: "baa_nomor", label: "Nomor BAK", required: true }], document: true, category: "BAK-PKS" },
  8: { action: "aktivasi", title: "Aktifkan layanan", fields: [{ key: "aktivasi_catatan", label: "Catatan aktivasi", type: "textarea", required: true }] },
  9: { action: "kirim_baa", title: "Kirim status aktivasi & BAA", fields: [{ key: "baa_nomor", label: "Nomor BAA", required: true }], document: true, category: "BAK-PKS" },
  10: { action: "terbitkan_invoice", title: "Terbitkan invoice", fields: [{ key: "invoice_nomor", label: "Nomor invoice", required: true }, { key: "invoice_nilai", label: "Nilai invoice (Rp)", type: "number", required: true }], document: true, category: "Kontrak" },
  11: { action: "kirim_invoice", title: "Kirim tagihan", fields: [{ key: "invoice_catatan", label: "Catatan pengiriman", type: "textarea" }] },
  12: { action: "konfirmasi_bayar", title: "Konfirmasi pembayaran", fields: [{ key: "bukti_pembayaran", label: "Referensi bukti pembayaran", type: "textarea", required: true }], document: true, category: "Dokumen Lain" },
};

export default function Sop2ActionModal({ item, session, onClose, onSuccess }) {
  const config = useMemo(() => CONFIG[item?.current_step], [item]);
  const [form, setForm] = useState({}); const [file, setFile] = useState(null); const [progress, setProgress] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { setForm({}); setFile(null); setProgress(0); setError(""); }, [item]);
  if (!item || !config) return null;
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const data = { ...form }; if (data.invoice_nilai !== undefined) data.invoice_nilai = Number(data.invoice_nilai); if (config.document) { if (!file) throw new Error("Dokumen pendukung wajib diunggah pada tahap ini."); const upload = new FormData(); upload.append("file", file); upload.append("kategori", config.category); upload.append("lokasi_id", String(item.lokasi_id || item.kontrak_induk_id)); const uploaded = await uploadDocument(session.token, upload, setProgress); data.document_id = uploaded?.id; data.document_name = uploaded?.nama_file || file.name; if (item.current_step === 12) data.bukti_pembayaran = `Dokumen #${uploaded?.id || "baru"}: ${file.name}`; } await completeServiceChangeStep(session.token, item.id, form.catatan, config.action, data); onSuccess?.(); onClose?.(); } catch (err) { setError(err.message || "Tahap SOP2 belum dapat disimpan."); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={() => !saving && onClose?.()} /><form onSubmit={submit} className="relative w-full max-w-lg rounded-2xl border border-gold-accent/25 bg-slate-900 p-6 shadow-2xl"><header className="mb-5 flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-widest text-gold-accent">Tahap {item.current_step} dari 12 · {item.kode_perubahan}</p><h2 className="mt-2 text-lg font-black text-white">{config.title}</h2><p className="mt-1 text-xs text-white/50">{item.nama_pelanggan} · {item.lokasi_nama}</p></div><button type="button" disabled={saving} onClick={onClose} className="text-white/50 hover:text-white"><X size={20} /></button></header><div className="space-y-4">{config.fields.map((field) => <label key={field.key} className="block text-sm text-slate-200">{field.label} {field.required && <span className="text-rose-300">*</span>}{field.type === "textarea" ? <textarea required={field.required} rows={4} value={form[field.key] || ""} onChange={(e) => set(field.key, e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/15 bg-slate-950/70 p-3 text-sm text-white outline-none focus:border-gold-accent" /> : <input required={field.required} type={field.type || "text"} min={field.type === "number" ? 1 : undefined} value={form[field.key] || ""} onChange={(e) => set(field.key, e.target.value)} className="mt-1.5 w-full rounded-xl border border-white/15 bg-slate-950/70 p-3 text-sm text-white outline-none focus:border-gold-accent" />}</label>)}{config.document && <label className="block text-sm text-slate-200">Dokumen pendukung *<input required type="file" accept=".pdf,image/*" onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-1.5 block w-full rounded-xl border border-dashed border-white/20 bg-slate-950/70 p-3 text-xs text-slate-300" />{progress > 0 && <span className="mt-1 block text-xs text-gold-accent">Upload {progress}%</span>}</label>}{error && <p className="rounded-lg border border-rose-400/25 bg-rose-500/10 p-3 text-sm text-rose-100">{error}</p>}</div><div className="mt-6 flex justify-end gap-3 border-t border-white/10 pt-5"><button type="button" disabled={saving} onClick={onClose} className="rounded-xl px-4 py-2 text-sm text-slate-300 hover:bg-white/10">Batal</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-gold-accent px-4 py-2.5 text-sm font-black text-slate-950 hover:bg-yellow-300 disabled:opacity-60">{saving ? <Loader2 size={16} className="animate-spin" /> : <CheckCircle2 size={16} />} Simpan tahap</button></div></form></div>;
}
